// <auto-generated />
using System;
using AuditedEntities.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditedEntities.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830235753_RemoveAuditTrailCascadeDelete")]
    partial class RemoveAuditTrailCascadeDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditedEntities.Data.Sample.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("AuditedEntities.Domain.AuditTrailEntry<AuditedEntities.Data.Sample.Product, int>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("FieldId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("ProductAuditTrailEntries", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("AuditTrailEntry<Product, int>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AuditedEntities.Data.Sample.ProductAuditTrailEntry", b =>
                {
                    b.HasBaseType("AuditedEntities.Domain.AuditTrailEntry<AuditedEntities.Data.Sample.Product, int>");

                    b.HasDiscriminator().HasValue("ProductAuditTrailEntry");
                });

            modelBuilder.Entity("AuditedEntities.Domain.AuditTrailEntry<AuditedEntities.Data.Sample.Product, int>", b =>
                {
                    b.HasOne("AuditedEntities.Data.Sample.Product", null)
                        .WithMany("AuditTrail")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AuditedEntities.Data.Sample.Product", b =>
                {
                    b.Navigation("AuditTrail");
                });
#pragma warning restore 612, 618
        }
    }
}
